#!/usr/bin/env bash
# 生成 THIRD_PARTY_NOTICES：枚举静态链入 pion-ipc 二进制的第三方 Go 模块，
# 逐个汇编「模块路径 + 版本 + SPDX 许可 + 版权行 + 许可全文」。
#
# 为什么这样做：pion-ipc 编成静态二进制经 6 个 @coclaw/pion-ipc-<平台> npm 包分发，
# 二进制里静态链接了一批第三方 Go 模块（pion 全家 + golang.org/x + 少量其它）。
# MIT/BSD/Apache 等宽松许可要求分发二进制时随附这些模块的版权声明与许可全文。
#
# 可复现性：
#   - 权威「已链接」模块集取自对真实二进制跑 `go version -m`（-ldflags="-s -w" 剥符号
#     不影响内嵌的 build info）。为不遗漏平台专属依赖，这里对全部 6 个发布目标交叉编译
#     后取并集（GOOS/GOARCH 列表须与 scripts/build-npm.sh 的 PLATFORMS 保持一致）。
#   - 许可全文取自本地 module cache（`go build` 会填充；路径经 `go mod download -json`
#     解析，稳妥处理大小写转义）。
#   - 遇到 copyleft（GPL/LGPL/AGPL/MPL/EPL/CDDL/SSPL）或无法识别的许可即报错退出，
#     绝不静默放行。
#
# 用法：
#   scripts/gen-notices.sh [-o OUTPUT]     # 默认写 stdout；-o 写文件
set -euo pipefail

OUT=""
while getopts "o:" opt; do
	case "$opt" in
		o) OUT="$OPTARG" ;;
		*) echo "Usage: $0 [-o OUTPUT]" >&2; exit 1 ;;
	esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

# 与 scripts/build-npm.sh PLATFORMS 对齐的 GOOS/GOARCH 集（二进制名无关，故此处只列 os/arch）。
# linux/arm 在下面构建时固定 GOARM=7，与 build-npm.sh 一致——避免 arm.5/6/7 build tag 差异
# 让两处链接到不同模块集。
TARGETS=(
	"linux amd64"
	"linux arm64"
	"linux arm"
	"darwin amd64"
	"darwin arm64"
	"windows amd64"
)

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "[notices] 交叉编译 ${#TARGETS[@]} 个目标并取已链接模块并集 ..." >&2
: > "$TMPDIR/deps.raw"
for t in "${TARGETS[@]}"; do
	read -r goos goarch <<< "$t"
	bin="$TMPDIR/pion-ipc-$goos-$goarch"
	# linux/arm 固定 GOARM=7（armv7l），与 build-npm.sh 的构建参数完全一致。
	goarm_env=""
	[ "$goarch" = "arm" ] && goarm_env="GOARM=7"
	env CGO_ENABLED=0 GOOS="$goos" GOARCH="$goarch" ${goarm_env} \
		go build -ldflags="-s -w" -o "$bin" ./cmd/pion-ipc
	# build info 里的 dep 行：dep <module> <version> <hash>
	go version -m "$bin" | awk '$1=="dep"{print $2"\t"$3}' >> "$TMPDIR/deps.raw"
done
sort -u "$TMPDIR/deps.raw" > "$TMPDIR/deps.txt"

MOD_COUNT="$(wc -l < "$TMPDIR/deps.txt" | tr -d ' ')"
echo "[notices] 第三方模块 ${MOD_COUNT} 个" >&2

# 识别许可类型（SPDX）。仅接受已知宽松许可；copyleft 或无法识别即失败。
classify_license() {
	local f="$1"
	# 带附加限制的 source-available 许可：正文常照抄 MIT/BSD 式宽松序言，却叠加使用限制，
	# 会被下面的宽松匹配误判放行。放在最前拦截：命中即报错交人工核实，绝不静默通过。
	if grep -qiE "Commons Clause|Business Source License|Elastic License|Functional Source License|used for Good, not Evil|non-commercial|noncommercial" "$f"; then
		echo "__RESTRICTED__"; return
	fi
	if grep -qiE "GNU (AFFERO )?GENERAL PUBLIC LICENSE|GNU LESSER GENERAL PUBLIC" "$f"; then
		echo "__COPYLEFT__"; return
	fi
	if grep -qiE "Mozilla Public License|Eclipse Public License|Common Development and Distribution License|Server Side Public License" "$f"; then
		echo "__COPYLEFT__"; return
	fi
	if grep -qi "Apache License" "$f"; then echo "Apache-2.0"; return; fi
	if grep -qi "Permission is hereby granted, free of charge" "$f"; then
		# ISC 与 MIT 都有此句；ISC 用 "copies of the software" 且缺 "without limitation"
		if grep -qi "ISC License" "$f"; then echo "ISC"; else echo "MIT"; fi
		return
	fi
	if grep -qi "Redistribution and use in source and binary forms" "$f"; then
		if grep -qiE "Neither the name|endorse or promote products" "$f"; then
			echo "BSD-3-Clause"
		else
			echo "BSD-2-Clause"
		fi
		return
	fi
	echo "__UNKNOWN__"
}

# 在模块目录里挑许可文件：优先 LICENSE，再退回常见变体。
find_license_file() {
	local dir="$1" f
	for f in LICENSE LICENSE.txt LICENSE.md LICENCE COPYING COPYING.txt; do
		[ -f "$dir/$f" ] && { echo "$dir/$f"; return 0; }
	done
	return 1
}

# 生成正文到临时文件，全部成功后再落地（避免半成品）。
BODY="$TMPDIR/notices.txt"
SEP="$(printf '=%.0s' {1..80})"
SUB="$(printf -- '-%.0s' {1..80})"

{
	echo "CoClaw pion-ipc — Third-Party Software Notices"
	echo "=============================================="
	echo ""
	echo "The pion-ipc binaries distributed in the @coclaw/pion-ipc-<platform> npm"
	echo "packages are statically linked with the third-party Go modules listed below."
	echo "Each module is provided under the license shown, reproduced in full."
	echo ""
	echo "This file is generated by scripts/gen-notices.sh — do not edit by hand."
	echo ""
	echo "Modules (${MOD_COUNT}):"
} > "$BODY"

# 第一遍：先解析全部条目、校验许可，收集摘要；任一失败立即退出。
declare -a ENTRY_MOD ENTRY_VER ENTRY_SPDX ENTRY_FILE
while IFS=$'\t' read -r mod ver; do
	[ -z "$mod" ] && continue
	dir="$(go mod download -json "${mod}@${ver}" 2>/dev/null | sed -n 's/.*"Dir": "\(.*\)",\?$/\1/p' | head -1)"
	if [ -z "$dir" ] || [ ! -d "$dir" ]; then
		echo "[notices] ERROR: 无法定位 ${mod}@${ver} 的 module cache 目录" >&2
		exit 1
	fi
	lf="$(find_license_file "$dir")" || {
		echo "[notices] ERROR: ${mod}@${ver} 未找到许可文件" >&2
		exit 1
	}
	spdx="$(classify_license "$lf")"
	case "$spdx" in
		__COPYLEFT__)
			echo "[notices] ERROR: ${mod}@${ver} 命中 copyleft 许可（$lf）——停止，需人工处置" >&2
			exit 1 ;;
		__RESTRICTED__)
			echo "[notices] ERROR: ${mod}@${ver} 命中带附加限制的 source-available 许可（$lf）——停止，需人工核实" >&2
			exit 1 ;;
		__UNKNOWN__)
			echo "[notices] ERROR: ${mod}@${ver} 许可无法识别（$lf）——停止，需人工核实" >&2
			exit 1 ;;
	esac
	ENTRY_MOD+=("$mod"); ENTRY_VER+=("$ver"); ENTRY_SPDX+=("$spdx"); ENTRY_FILE+=("$lf")
	printf '  - %s %s (%s)\n' "$mod" "$ver" "$spdx" >> "$BODY"
done < "$TMPDIR/deps.txt"

# 第二遍：逐条输出许可全文。
for i in "${!ENTRY_MOD[@]}"; do
	{
		echo ""
		echo "$SEP"
		echo "${ENTRY_MOD[$i]} ${ENTRY_VER[$i]}"
		echo "License: ${ENTRY_SPDX[$i]}"
		echo "$SUB"
		cat "${ENTRY_FILE[$i]}"
	} >> "$BODY"
done

if [ -n "$OUT" ]; then
	mv "$BODY" "$OUT"
	echo "[notices] 已写入 $OUT（${MOD_COUNT} 个模块）" >&2
else
	cat "$BODY"
fi
